"""
app/models/image.py
─────────────────────────────────────────────────────────────────────────────
poster_images table — lightweight image registry for the chat-based UI.

One row per image — uploaded by the user, generated by the AI, or promoted
to the approved set. The source column tells the review UI which gallery
to render it in.
─────────────────────────────────────────────────────────────────────────────
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import ARRAY, BigInteger, DateTime, Enum, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class ImageSource(str, enum.Enum):
    UPLOAD    = "upload"
    GENERATED = "generated"
    APPROVED  = "approved"
    REJECTED  = "rejected"


class PosterImage(Base):
    __tablename__ = "poster_images"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    filename: Mapped[str] = mapped_column(String(300), nullable=False)
    storage_path: Mapped[str] = mapped_column(String(500), nullable=False)
    url: Mapped[str] = mapped_column(String(1000), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)

    source: Mapped[ImageSource] = mapped_column(
        Enum(
            ImageSource,
            name="image_source_enum",
            create_type=False,
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=False,
        default=ImageSource.UPLOAD,
        index=True,
    )

    caption: Mapped[str | None] = mapped_column(Text, nullable=True)
    platform: Mapped[str | None] = mapped_column(String(40), nullable=True)
    platforms: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    scheduled_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    session_id: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    prompt: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        return f"<PosterImage id={self.id} source={self.source.value}>"
